package:
  name: openmembrane
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - pyunitwizard
  - openmm
  - nglview
  - ipywidgets <8
  - molsysmt
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library... '
  dev_url: https://github.com/uibcdf/OpenMembrane
  doc_url: https://uibcdf.org/OpenMembrane
